---
# automations.yaml

- id: turn_on_wc_light
  alias: "Light WC on"
  trigger:
    - platform: state
      entity_id: binary_sensor.ewelink_ms01_motion
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.wc_light
      state: "off"
    - condition: time
      after: "07:00:00"
      before: "20:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.wc_light
#
#- alias: "Light WC off"
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.motion_sensor_1_occupancy
#      for:
#        minutes: 1
#      to: "off"
#  condition:
#    - condition: state
#      entity_id: switch.wc_light
#      state: "on"
#  action:
#    - service: switch.turn_off
#      entity_id: switch.wc_light
