# automations.yaml

# akvarko dimmer PID regulace teploty
#- alias: zelva heatlamp
#  trigger:
#    - platform: state
#      entity_id: sensor.zelva_right_temperature
#  condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: light.zelva_teplo
#          state: 'on'
#        #- condition: time
#        #  after: '10:00:00'
#        #  before: '18:00:00'
#        #- condition: numeric_state
#        #  entity_id: sensor.zelva_right_temperature
#        #  above: 30
#  action:
#    service: light.turn_on
#    entity_id: light.zelva_teplo
#    data_template:
#      # decrease brightness with increasing temp
#      # PID nastaven na stred teploty 28
#      brightness: >
#        {% set target_temp = 28 %}
#        {% set max_temp = target_temp + 4 %}
#        {% set current_temp = states('sensor.zelva_right_temperature')|float %}
#        {% if current_temp < target_temp - 4 %}255
#        {% elif current_temp < max_temp %}{{ ((max_temp - current_temp) * (256/8))|int }}
#        {% else %} 16
#        {% endif %}

# samsung TV switch to
# TODO
# - alias: samsung switch channel
#   trigger:
#     - platform: time
#       at: "06:31:00"
#   action:
#     service: script.tv_channel_decko
#     data:
#       title: 'TV State change'
#       message: 'The CT-D is on!'

# Turn off lights when everybody leaves the house
- alias: 'Away Mode switch light'
  trigger:
    platform: state
    entity_id: group.all_persons
    to: 'not_home'
    for:
      minutes: 15
  condition:
    condition: time
    before: '09:00:00'
  action:
    service: light.turn_off
    entity_id: group.all_lights

# Christmas light ON/OFF
#- alias: christmas_light_ON
#  trigger:
#    platform: sun
#    event: sunset
#  action:
#    service: switch.turn_on
#    entity_id: switch.christmas_light
#
#- alias: christmas_light_OFF
#  trigger:
#    platform: time
#    at: "23:00:00"
#  action:
#    service: switch.turn_off
#    entity_id: switch.christmas_light

# Kids room light OFF
- id: kids_room_light_off
  alias: "Kids room Light Off"
  trigger:
      platform: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: light.kids_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kids_light

# Hall room light OFF
- alias: "Hall room light Off"
  trigger:
      at: "22:00:00"
      platform: time
  condition:
    - condition: state
      entity_id: light.hall_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hall_light

#- alias: "Power state on HA start-up"
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: mqtt.publish
#      data:
#        topic: "sonoffs/cmnd/state"
#        payload: ""

#- alias: "Enable MQTT discovery for all devices"
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: mqtt.publish
#      data:
#        topic: "cmnd/sonoffs/SetOption19"
#        payload: "1"
