# configuration.yaml

# Turn off lights when everybody leaves the house
- alias: 'Rule - Away Mode switch light'
  trigger:
    platform: state
    entity_id: device_tracker.jirka_iphone
    to: 'not_home'
  condition:
    - condition: time
      before: '08:00:00'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- id: pokojicek_light_off
  alias: "Pokojicek Light Off"
  trigger:
      at: "20:00:00"
      platform: time
  action:
    - service: light.turn_off
      entity_id: light.kitchen_light

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""

- alias: "Enable MQTT discovery for all devices"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/SetOption19"
        payload: "1"
