homeassistant:
  name: Domov
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_alt
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

lovelace:
  mode: yaml

person:
  - name: jirka
    id: jirka
    user_id: 9b636effb9394d9099f8d4d0a36999fd
    device_trackers:
      - device_tracker.jirka
  - name: lucka
    id: lucka
    device_trackers:
      - device_tracker.jirka_iphone_2
  - name: terezka
    id: terezka
    device_trackers:
      - device_tracker.tereza_iphone_2

# Example configuration.yaml entry
mikrotik:
  - host: 192.168.2.1
    username: admin
    password: !secret mikrotik_password

# Configure Netatmo integration
netatmo:
  client_id: !secret netatmo_api_key
  client_secret: !secret netatmo_secret_key

# convert switch to light
light:
  - platform: switch
    name: hall light
    entity_id: switch.hall_light
  - platform: switch
    name: wc light
    entity_id: switch.wc_light

# Amazon Echo configuration.yaml entry
emulated_hue:
  host_ip: 192.168.2.4
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
  entities:
    light.bed_light:
      name: "Bed light"
      hidden: false
    light.kitchen_light:
      name: "Kitchen light"
      hidden: false
    light.kids_light:
      name: "Kids light"
      hidden: false
    light.wc_light:
      name: "WC light"
      hidden: false
    light.hall_light:
      name: "Hall light"
      hidden: false
    switch.kids_tv:
      name: "Kids TV"
      hidden: false
    group.all_lights:
      name: "All lights"

# HomeKit integration
homekit:
  filter:
    include_domains:
      - light
      - media_player

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
    entities:
      - light.zelva_teplo
  exclude:
    entities:
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_max_temp
      - sensor.netatmo_indoor_min_temp
      - sensor.netatmo_outdoor_max_temp
      - sensor.netatmo_outdoor_min_temp
      - sensor.netatmo_pokojicek_max_temp
      - sensor.netatmo_pokojicek_min_temp

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

scene:
  - name: All lights OFF
    entities:
      light.bed_light: off
      light.kitchen_light: off
      light.wc_light: off
      light.hall_light: off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
