homeassistant:
  name: Domov
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_alt
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

# convert switch to light
light:
  - platform: switch
    name: wc light
    entity_id: switch.wc_light

# Amazon Echo configuration.yaml entry
emulated_hue:
  host_ip: 192.168.2.4
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
  entities:
    light.bed_light:
      name: "Bed light"
      hidden: false
    light.kitchen_light:
      name: "Kitchen light"
      hidden: false
    light.kids_light:
      name: "Kids light"
      hidden: false
    light.wc_light:
      name: "WC light"
      hidden: false
    group.all_lights:
      name: "All lights"

# HomeKit integration
homekit:
  filter:
    include_domains:
      - light
      - media_player

# Xiomi temperature
ble_monitor:
  devices:
    - mac: "A4:C1:38:6C:60:9F"
      name: "Kids Room Temp"
      encryption_key: "b5d252328a71e89ec992b80ddab04ed1"
    - mac: "A4:C1:38:47:B6:BC"
      name: "Living Room Temp"
      encryption_key: "adbbba3b9a996f0db4ce40db53911b14"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
