homeassistant:
  name: Domov
  latitude: 50.1576534
  longitude: 14.5168246
  elevation: 225
  unit_system: metric
  time_zone: Europe/Prague

  customize: !include customize.yaml

person:
  - name: jirka
    id: jirka
    user_id: 9b636effb9394d9099f8d4d0a36999fd
    device_trackers:
      - device_tracker.jirka_iphone
  - name: lucka
    id: lucka
    device_trackers:
      - device_tracker.iphone_lucka
  - name: terezka
    id: terezka
    device_trackers:
      - device_tracker.tereza_iphone

# Example configuration.yaml entry
mikrotik:
  - host: 192.168.2.1
    username: admin
    password: !secret mikrotik_password

# Configure Netatmo integration
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

media_player:
  - platform: samsungtv
    host: 192.168.2.30
    port: 8001
    name: tv

# konverze switch na light
light:
  - platform: switch
    name: hall light
    entity_id: switch.hall_light
  - platform: switch
    name: wc light
    entity_id: switch.wc_light

# Amazon Echo configuration.yaml entry
emulated_hue:
  host_ip: 192.168.2.4
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
  entities:
    light.bed_light:
      name: "Bed light"
      hidden: false
    light.kitchen_light:
      name: "Kitchen light"
      hidden: false
    light.kids_light:
      name: "Kids light"
      hidden: false
    light.wc_light:
      name: "WC light"
      hidden: false
    light.hall_light:
      name: "Hall light"
      hidden: false
    switch.kids_tv:
      name: "Kids TV"
      hidden: false
    group.all_lights:
      name: "All lights"

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
discovery:
  ignore:
    - samsung_tv
  enable:
    - homekit

# iPhone integration
# disable, umi akorat battery level
# ios:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

scene:
  - name: All lights OFF
    entities:
      light.bed_light: off
      light.kitchen_light: off
      light.wc_light: off
      light.hall_light: off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
