homeassistant:
  name: Domov
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_alt
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

lovelace:
  mode: yaml

person:
  - name: jirka
    id: jirka
    user_id: 9b636effb9394d9099f8d4d0a36999fd
    device_trackers:
      - device_tracker.jirka_iphone
  - name: lucka
    id: lucka
    device_trackers:
      - device_tracker.iphone_lucka
  - name: terezka
    id: terezka
    device_trackers:
      - device_tracker.lucka_iphone_2

# Example configuration.yaml entry
mikrotik:
  - host: 192.168.2.1
    username: homeassistant
    password: homeassistant

# convert switch to light
light:
  - platform: switch
    name: hall light
    entity_id: switch.hall_light
  - platform: switch
    name: wc light
    entity_id: switch.wc_light

# Amazon Echo configuration.yaml entry
emulated_hue:
  host_ip: 192.168.2.4
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
  entities:
    light.bed_light:
      name: "Bed light"
      hidden: false
    light.kitchen_light:
      name: "Kitchen light"
      hidden: false
    light.kids_light:
      name: "Kids light"
      hidden: false
    light.wc_light:
      name: "WC light"
      hidden: false
    group.all_lights:
      name: "All lights"

# HomeKit integration
homekit:
  filter:
    include_domains:
      - light
      - media_player

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor

# Xiomi temperature
ble_monitor:
  devices:
    - mac: "A4:C1:38:6C:60:9F"
      name: "Kids Room Temp"
      encryption_key: "b5d252328a71e89ec992b80ddab04ed1"
    - mac: "A4:C1:38:47:B6:BC"
      name: "Living Room Temp"
      encryption_key: "adbbba3b9a996f0db4ce40db53911b14"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

scene:
  - name: All lights OFF
    entities:
      light.bed_light: off
      light.kitchen_light: off
      light.wc_light: off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
