title: Domov
views:
  - path: default_view
    title: Home
    badges:
      - entity: sun.sun
    cards:
      - type: history-graph
        title: 'Kids temperature'
        entities:
          - sensor.netatmo_pokojicek_temperature
          - sensor.sonoff_pow_tv_temperature
          - sensor.zelva_left_temperature
      - type: entities
        entities:
          - light.kitchen_light
          - light.bed_light
          - switch.flower
          - climate.netatmo_living_room
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
        title: Bedroom
        show_header_toggle: true

      - type: entities
        title: Kids room
        show_header_toggle: true
        entities:
          - light.kids_light
          - switch.kids_tv
          - sensor.sonoff_pow_tv_power
          - sensor.sonoff_pow_tv_temperature
          - sensor.sonoff_pow_tv_humidity
          - climate.netatmo_kids_room
          - sensor.netatmo_pokojicek_health
          - sensor.netatmo_pokojicek_co2
          - sensor.netatmo_pokojicek_temperature
          - sensor.netatmo_pokojicek_humidity
          - sensor.netatmo_pokojicek_noise

      - type: entities
        entities:
          - person.jirka
          - person.lucka
          - person.terezka
          - device_tracker.iphone_lucka
          - device_tracker.jirka_iphone
          - device_tracker.tereza_iphone
        title: all_persons
        show_header_toggle: true

      - type: entities
        entities:
          - light.hall_light
        title: Hall
        show_header_toggle: true
      - type: entities
        entities:
          - climate.netatmo_bathroom
          - light.wc_light
          - switch.wc_fan
        title: Bathroom
        show_header_toggle: true

      - type: entities
        entities:
          - sensor.netatmo_outdoor_battery
          - sensor.netatmo_outdoor_battery_percent
          - sensor.netatmo_outdoor_humidity
          - sensor.netatmo_outdoor_temperature
        title: Balkon
        show_header_toggle: true

      - type: entities
        title: Akvarko
        show_header_toggle: true
        entities:
          - switch.zelva_uvb
          - light.zelva_teplo
          - sensor.zelva_left_temperature
          - sensor.zelva_right_temperature
          - sensor.zelva_humidity

      - type: thermostat
        entity: climate.netatmo_kotelna
      - type: thermostat
        entity: climate.netatmo_bathroom
      - type: thermostat
        entity: climate.netatmo_living_room
      - type: thermostat
        entity: climate.netatmo_kids_room

      - type: entities
        entities:
          - automation.samsung_switch_channel
          - automation.away_mode_switch_light
          - automation.kids_room_light_off
          - automation.hall_room_light_off
        title: Automatizace
      - type: entities
        entities:
          - scene.all_lights_off
        title: Scéna
      - type: entities
        entities:
          - script.tv_channel_decko
        title: Skript
      - type: weather-forecast
        entity: weather.domov
