title: Domov
views:
  - path: default_view
    title: Home
    badges:
      - entity: sun.sun
    cards:
      - type: history-graph
        title: "Temperatures in the last 48 hours"
        hours_to_show: 48
        entities:
          - entity: sensor.ble_temperature_kids_room_temp
            name: kids-room
          - entity: sensor.ble_temperature_living_room_temp
            name: living-room
          - sensor.0x00124b0023b48441_temperature

      - type: entities
        title: Living room
        entities:
          - light.kitchen_light
          - light.bed_light
          - sensor.ble_temperature_living_room_temp
          - sensor.ble_humidity_living_room_temp
          - sensor.0x00124b0023b48441_temperature

        show_header_toggle: true

      - type: entities
        title: Kids room
        show_header_toggle: true
        entities:
          - light.kids_light
          - sensor.ble_temperature_kids_room_temp
          - sensor.ble_humidity_kids_room_temp

      - type: entities
        title: all_persons
        entities:
          - person.jirka
          - person.lucka
          - person.terezka
          - device_tracker.iphone_lucka
          - device_tracker.jirka_iphone
          - device_tracker.tereza_iphone
        show_header_toggle: true

      - type: entities
        title: Bathroom
        entities:
          - light.wc_light
          - switch.wc_fan
        show_header_toggle: true

      - type: entities
        title: Balkon
        entities:
          - switch.christmas
        show_header_toggle: true

      - type: entities
        title: Automatizace
        entities:
          - automation.away_mode_switch_light
          - automation.kids_room_light_off

      - type: entities
        entities:
          - scene.all_lights_off
        title: Scéna

      - type: weather-forecast
        entity: weather.domov
