title: Domov
views:
  - path: default_view
    title: Home
    badges:
      - entity: sun.sun
    cards:
      - type: history-graph
        title: 'Kids temperature'
        entities:
          - sensor.netatmo_pokojicek_temperature
          - sensor.sonoff_pow_tv_temperature
          - sensor.zelva_left_temperature

      - type: entities
        title: Bedroom
        entities:
          - light.kitchen_light
          - light.bed_light
          - switch.flower
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
        show_header_toggle: true

      - type: entities
        title: Kids room
        show_header_toggle: true
        entities:
          - light.kids_light
          - sensor.netatmo_pokojicek_health
          - sensor.netatmo_pokojicek_co2
          - sensor.netatmo_pokojicek_temperature
          - sensor.netatmo_pokojicek_humidity
          - sensor.netatmo_pokojicek_noise

      - type: entities
        title: all_persons
        entities:
          - person.jirka
          - person.lucka
          - person.terezka
          - device_tracker.iphone_lucka
          - device_tracker.jirka_iphone
          - device_tracker.tereza_iphone
        show_header_toggle: true

      - type: entities
        title: Hall
        entities:
          - light.hall_light
        show_header_toggle: true

      - type: entities
        title: Bathroom
        entities:
          - light.wc_light
          - switch.wc_fan
        show_header_toggle: true

      - type: entities
        title: Balkon
        entities:
          - switch.christmas_balkon
          - sensor.netatmo_outdoor_battery
          - sensor.netatmo_outdoor_battery_percent
          - sensor.netatmo_outdoor_humidity
          - sensor.netatmo_outdoor_temperature
        show_header_toggle: true

      - type: entities
        title: Akvarko
        show_header_toggle: true
        entities:
          - switch.emmet
          - switch.dortik

      - type: entities
        title: Automatizace
        entities:
          - automation.away_mode_switch_light
          - automation.kids_room_light_off
          - automation.hall_room_light_off

      - type: entities
        entities:
          - scene.all_lights_off
        title: Scéna

      - type: weather-forecast
        entity: weather.domov
