homeassistant:
  name: Semanky
  unit_system: metric
  country: CZ
  time_zone: Europe/Prague

# Utility meter
utility_meter:
  grid_export_energy_daily:
    source: sensor.shelly_pro3em_total_active_returned_energy
    cycle: daily
  grid_import_energy_daily:
    source: sensor.shelly_pro3em_total_active_energy
    cycle: daily
  pv_free_daily:
    source: sensor.pv_free_power
    cycle: daily

sensor:
  - platform: history_stats
    name: Cerpadlo run time
    entity_id: binary_sensor.greenbono_k1_pool_pump
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
